version: '3'

services: 
  webdav:
    build: 
      context: .
      dockerfile: ./configs/Dockerfile
      args:
        DAVUSER: ${DAVUSER}
        DAVPASS:  ${DAVPASSWD}
        TMPFOLDER: ${TMPFOLDER}     
    container_name: 'webdav'
    volumes:
      - ./configs/webdav.conf:/etc/nginx/conf.d/default.conf
      - ${HOSTFOLDER}:/webfolder
    image: webdav
    restart: always
    ports: 
      - '$PORT:80'
      - "$PORTSSL:443"
